#!/usr/bin/env bash
# Cross-compiles pedithelper for the target architectures and regenerates
# pedit.sh -- the pastable bash snippet -- with the resulting static
# binaries embedded as base64. Run this after any change under
# cmd/pedithelper or the internal packages it uses (wire, proto).
set -euo pipefail
cd "$(dirname "$0")"

ARCHES=(amd64 arm64 386 arm)
OUT=pedit.sh
BUILD_DIR=$(mktemp -d)
trap 'rm -rf "$BUILD_DIR"' EXIT

declare -A BLOB SHA SIZE
echo "building pedithelper for: ${ARCHES[*]}"
for arch in "${ARCHES[@]}"; do
  bin="$BUILD_DIR/pedithelper.$arch"
  CGO_ENABLED=0 GOOS=linux GOARCH="$arch" go build -trimpath -ldflags="-s -w" -o "$bin" ./cmd/pedithelper
  BLOB[$arch]=$(base64 -w0 "$bin")
  SHA[$arch]=$(sha256sum "$bin" | cut -d' ' -f1)
  SIZE[$arch]=$(stat -c%s "$bin")
  echo "  linux/$arch: ${SIZE[$arch]} bytes, sha256 ${SHA[$arch]}"
done

{
  cat <<'HEADER'
# pedit -- ship a file to your ssh-agent over a forwarded agent socket
# (RFC 9987 SSH_AGENTC_EXTENSION), run a command on it at "home", get the
# (possibly modified) result back. Paste this into .bashrc, or `source` it,
# on any host you ssh -A through -- no install step, no root, no
# dependency beyond coreutils (base64/mktemp/sha256sum). Generated by
# pedit/build.sh -- do not hand-edit, re-run build.sh instead.
#
# Usage:
#   pedit [-p profile] [-o outfile] <file>
#     -p profile   home-side profile to invoke (default: edit)
#     -o outfile   write the result somewhere other than <file>
#
#   pup <file>                       copy <file> to the transfer directory at
#                                    home. Never overwrites: if the name is
#                                    already taken there, it is refused.
#   pdown [-o outfile] [-f] [name]   fetch <name> from that same directory.
#     (no name)                      list what is staged there
#     -o outfile                     write somewhere other than ./<name>
#     -f                             allow overwriting an existing local file
#
# Requires: $SSH_AUTH_SOCK set and agent forwarding (-A / ForwardAgent yes)
# enabled at every hop back to a host running peditagentd.

_pedit_cache_dir="${TMPDIR:-/tmp}/.pedit-$(id -u)"

HEADER

  for arch in "${ARCHES[@]}"; do
    echo "_pedit_blob_${arch}=\"${BLOB[$arch]}\""
    echo "_pedit_sha256_${arch}=\"${SHA[$arch]}\""
  done
  echo

  cat <<'BODY'
_pedit_ensure_helper() {
  local arch blob sha bin
  arch=$(uname -m)
  case "$arch" in
    x86_64)          arch=amd64 ;;
    aarch64|arm64)   arch=arm64 ;;
    i386|i686)       arch=386 ;;
    armv6l|armv7l)   arch=arm ;;
    *)
      echo "pedit: unsupported architecture: $arch" >&2
      return 1
      ;;
  esac

  eval "blob=\"\${_pedit_blob_${arch}:-}\""
  eval "sha=\"\${_pedit_sha256_${arch}:-}\""
  if [ -z "$blob" ]; then
    echo "pedit: no embedded helper for architecture $arch" >&2
    return 1
  fi

  mkdir -p -m 700 "$_pedit_cache_dir" || return 1
  bin="$_pedit_cache_dir/pedithelper-$arch-$sha"
  if [ ! -x "$bin" ] || [ "$(sha256sum "$bin" 2>/dev/null | cut -d' ' -f1)" != "$sha" ]; then
    ( umask 077
      printf '%s' "$blob" | base64 -d > "$bin.tmp.$$" ) || return 1
    if [ "$(sha256sum "$bin.tmp.$$" | cut -d' ' -f1)" != "$sha" ]; then
      echo "pedit: checksum mismatch decoding embedded helper, refusing to run it" >&2
      rm -f "$bin.tmp.$$"
      return 1
    fi
    chmod 700 "$bin.tmp.$$"
    mv "$bin.tmp.$$" "$bin"
  fi
  printf '%s' "$bin"
}

pedit() {
  local profile=edit outfile= file= opt OPTARG OPTIND
  while getopts ":p:o:" opt; do
    case "$opt" in
      p) profile=$OPTARG ;;
      o) outfile=$OPTARG ;;
      *) echo "usage: pedit [-p profile] [-o outfile] <file>" >&2; return 2 ;;
    esac
  done
  shift $((OPTIND - 1))
  file=${1:-}
  if [ -z "$file" ]; then
    echo "usage: pedit [-p profile] [-o outfile] <file>" >&2
    return 2
  fi
  if [ ! -r "$file" ]; then
    echo "pedit: cannot read $file" >&2
    return 1
  fi
  if [ -z "${SSH_AUTH_SOCK:-}" ]; then
    echo "pedit: \$SSH_AUTH_SOCK is not set -- is agent forwarding (-A) enabled?" >&2
    return 1
  fi
  : "${outfile:=$file}"

  local helper
  helper=$(_pedit_ensure_helper) || return 1
  "$helper" send "$SSH_AUTH_SOCK" "$profile" "$file" "$outfile"
}

# pup -- push a file up to the transfer directory at home. Nothing runs
# there and nothing comes back; the empty outfile argument is what tells
# the helper no content is expected in reply.
pup() {
  local file=${1:-}
  if [ -z "$file" ] || [ $# -gt 1 ]; then
    echo "usage: pup <file>" >&2
    return 2
  fi
  if [ ! -r "$file" ]; then
    echo "pup: cannot read $file" >&2
    return 1
  fi
  if [ -z "${SSH_AUTH_SOCK:-}" ]; then
    echo "pup: \$SSH_AUTH_SOCK is not set -- is agent forwarding (-A) enabled?" >&2
    return 1
  fi

  local helper
  helper=$(_pedit_ensure_helper) || return 1
  "$helper" send "$SSH_AUTH_SOCK" pup "$file" ""
}

# pdown -- pull a file down from that same directory. With no name it lists
# what is available instead.
pdown() {
  local outfile= force=0 name= have_name=0 opt OPTARG OPTIND
  # getopts stops at the first non-option word, so a single pass would
  # silently ignore anything after the name -- "pdown app.conf -f" would
  # look like it worked and then not force. Alternate between parsing
  # options and taking the name so either order works.
  while [ $# -gt 0 ]; do
    OPTIND=1
    while getopts ":o:f" opt; do
      case "$opt" in
        o) outfile=$OPTARG ;;
        f) force=1 ;;
        *) echo "usage: pdown [-o outfile] [-f] [name]" >&2; return 2 ;;
      esac
    done
    shift $((OPTIND - 1))
    if [ $# -gt 0 ]; then
      if [ "$have_name" -eq 1 ]; then
        echo "pdown: fetches one file at a time" >&2
        echo "usage: pdown [-o outfile] [-f] [name]" >&2
        return 2
      fi
      name=$1
      have_name=1
      shift
    fi
  done
  if [ -z "${SSH_AUTH_SOCK:-}" ]; then
    echo "pdown: \$SSH_AUTH_SOCK is not set -- is agent forwarding (-A) enabled?" >&2
    return 1
  fi
  # Default to the same basename in the current directory. The far end
  # sends back only a single path element, so this cannot land elsewhere.
  : "${outfile:=$name}"

  local helper
  helper=$(_pedit_ensure_helper) || return 1
  "$helper" fetch "$SSH_AUTH_SOCK" "$name" "$outfile" "$force"
}
BODY
} > "$OUT"

chmod 644 "$OUT"
echo "wrote $OUT"
